/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;
import java.util.*;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author lucia
 */
public class JThreadRelay extends javax.swing.JFrame {
    ArrayList<Thread> threads;
    ArrayList<Runner> runners;
    Timer controllo; // timer che controlla ogni a secondo della velocità i threads
    /**
     * Creates new form JThreadRelay
     */
    public JThreadRelay() {
        initComponents();
     threads = new   ArrayList<>();
     runners = new   ArrayList<>();
     controllo =null;
    }

    //metodi
    private void AggiornaPrgb( Runner r, javax.swing.JProgressBar bar, javax.swing.JLabel lbl){
       int n= r.getI();
       bar.setValue(n);
       
       if (n==0){
           lbl.setText("0");
       } else if (n>= 100) {
           lbl.setText("Fine");
       } else lbl.setText(String.valueOf(n));
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpnlRunner1 = new javax.swing.JPanel();
        lblRunnerIcon1 = new javax.swing.JLabel();
        prgRunner1 = new javax.swing.JProgressBar();
        JpnlButton = new javax.swing.JPanel();
        cmbVelocita = new javax.swing.JComboBox<>();
        btnAvvia = new javax.swing.JButton();
        btnSospendere = new javax.swing.JButton();
        btnRiprendi = new javax.swing.JButton();
        btnFerma = new javax.swing.JButton();
        JpnlRunnerTimer1 = new javax.swing.JPanel();
        lblRunner1 = new javax.swing.JLabel();
        lblRunnerTimer1 = new javax.swing.JLabel();
        JpnlRunnerTimer2 = new javax.swing.JPanel();
        lblRunner2 = new javax.swing.JLabel();
        lblRunnerTimer2 = new javax.swing.JLabel();
        JpnlRunnerTimer3 = new javax.swing.JPanel();
        lblRunner3 = new javax.swing.JLabel();
        lblRunnerTimer3 = new javax.swing.JLabel();
        JpnlRunner2 = new javax.swing.JPanel();
        lblRunnerIcon2 = new javax.swing.JLabel();
        prgRunner2 = new javax.swing.JProgressBar();
        JpnlRunner3 = new javax.swing.JPanel();
        lblRunnerIcon3 = new javax.swing.JLabel();
        prgRunner3 = new javax.swing.JProgressBar();
        JpnlRunner4 = new javax.swing.JPanel();
        lblRunnerIcon4 = new javax.swing.JLabel();
        prgRunner4 = new javax.swing.JProgressBar();
        JpnlRunnerTimer4 = new javax.swing.JPanel();
        lblRunner4 = new javax.swing.JLabel();
        lblRunnerTimer4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        JpnlRunner1.setPreferredSize(new java.awt.Dimension(460, 90));
        JpnlRunner1.setLayout(null);

        lblRunnerIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/Runner.png"))); // NOI18N
        JpnlRunner1.add(lblRunnerIcon1);
        lblRunnerIcon1.setBounds(10, 20, 70, 60);
        JpnlRunner1.add(prgRunner1);
        prgRunner1.setBounds(10, 10, 450, 80);

        getContentPane().add(JpnlRunner1);
        JpnlRunner1.setBounds(0, 0, 480, 100);

        JpnlButton.setPreferredSize(new java.awt.Dimension(650, 80));

        cmbVelocita.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cmbVelocita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Slow", "Regular", "Fast" }));
        cmbVelocita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVelocitaActionPerformed(evt);
            }
        });

        btnAvvia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnAvvia.setText("Avvia");
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });

        btnSospendere.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnSospendere.setText("Sospendere");
        btnSospendere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSospendereActionPerformed(evt);
            }
        });

        btnRiprendi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnRiprendi.setText("Riprende");
        btnRiprendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiprendiActionPerformed(evt);
            }
        });

        btnFerma.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnFerma.setText("Ferma");
        btnFerma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnlButtonLayout = new javax.swing.GroupLayout(JpnlButton);
        JpnlButton.setLayout(JpnlButtonLayout);
        JpnlButtonLayout.setHorizontalGroup(
            JpnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlButtonLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cmbVelocita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnAvvia)
                .addGap(53, 53, 53)
                .addComponent(btnSospendere)
                .addGap(35, 35, 35)
                .addComponent(btnRiprendi)
                .addGap(39, 39, 39)
                .addComponent(btnFerma)
                .addGap(56, 56, 56))
        );
        JpnlButtonLayout.setVerticalGroup(
            JpnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnlButtonLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(JpnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVelocita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRiprendi)
                    .addComponent(btnFerma)
                    .addComponent(btnSospendere)
                    .addComponent(btnAvvia))
                .addGap(26, 26, 26))
        );

        getContentPane().add(JpnlButton);
        JpnlButton.setBounds(0, 400, 650, 80);

        JpnlRunnerTimer1.setBackground(new java.awt.Color(209, 226, 243));
        JpnlRunnerTimer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 226, 243)));
        JpnlRunnerTimer1.setForeground(new java.awt.Color(255, 255, 255));
        JpnlRunnerTimer1.setPreferredSize(new java.awt.Dimension(150, 90));

        lblRunner1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblRunner1.setText("Runner 1");

        lblRunnerTimer1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRunnerTimer1.setText("0");

        javax.swing.GroupLayout JpnlRunnerTimer1Layout = new javax.swing.GroupLayout(JpnlRunnerTimer1);
        JpnlRunnerTimer1.setLayout(JpnlRunnerTimer1Layout);
        JpnlRunnerTimer1Layout.setHorizontalGroup(
            JpnlRunnerTimer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlRunnerTimer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(lblRunnerTimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        JpnlRunnerTimer1Layout.setVerticalGroup(
            JpnlRunnerTimer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlRunnerTimer1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(JpnlRunnerTimer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner1)
                    .addComponent(lblRunnerTimer1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(JpnlRunnerTimer1);
        JpnlRunnerTimer1.setBounds(480, 10, 150, 80);

        JpnlRunnerTimer2.setBackground(new java.awt.Color(209, 226, 243));
        JpnlRunnerTimer2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 226, 243)));
        JpnlRunnerTimer2.setPreferredSize(new java.awt.Dimension(150, 90));

        lblRunner2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblRunner2.setText("Runner 2");

        lblRunnerTimer2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRunnerTimer2.setText("0");

        javax.swing.GroupLayout JpnlRunnerTimer2Layout = new javax.swing.GroupLayout(JpnlRunnerTimer2);
        JpnlRunnerTimer2.setLayout(JpnlRunnerTimer2Layout);
        JpnlRunnerTimer2Layout.setHorizontalGroup(
            JpnlRunnerTimer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlRunnerTimer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblRunnerTimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        JpnlRunnerTimer2Layout.setVerticalGroup(
            JpnlRunnerTimer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnlRunnerTimer2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(JpnlRunnerTimer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner2)
                    .addComponent(lblRunnerTimer2))
                .addGap(28, 28, 28))
        );

        getContentPane().add(JpnlRunnerTimer2);
        JpnlRunnerTimer2.setBounds(480, 100, 150, 90);

        JpnlRunnerTimer3.setBackground(new java.awt.Color(209, 226, 243));
        JpnlRunnerTimer3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 226, 243)));
        JpnlRunnerTimer3.setPreferredSize(new java.awt.Dimension(150, 90));

        lblRunner3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblRunner3.setText("Runner 3");

        lblRunnerTimer3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRunnerTimer3.setText("0");

        javax.swing.GroupLayout JpnlRunnerTimer3Layout = new javax.swing.GroupLayout(JpnlRunnerTimer3);
        JpnlRunnerTimer3.setLayout(JpnlRunnerTimer3Layout);
        JpnlRunnerTimer3Layout.setHorizontalGroup(
            JpnlRunnerTimer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlRunnerTimer3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblRunnerTimer3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        JpnlRunnerTimer3Layout.setVerticalGroup(
            JpnlRunnerTimer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnlRunnerTimer3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(JpnlRunnerTimer3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner3)
                    .addComponent(lblRunnerTimer3))
                .addGap(28, 28, 28))
        );

        getContentPane().add(JpnlRunnerTimer3);
        JpnlRunnerTimer3.setBounds(480, 200, 150, 90);

        JpnlRunner2.setLayout(null);

        lblRunnerIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/Runner2.png"))); // NOI18N
        JpnlRunner2.add(lblRunnerIcon2);
        lblRunnerIcon2.setBounds(10, 10, 80, 70);
        JpnlRunner2.add(prgRunner2);
        prgRunner2.setBounds(10, 0, 450, 90);

        getContentPane().add(JpnlRunner2);
        JpnlRunner2.setBounds(0, 100, 480, 90);

        JpnlRunner3.setPreferredSize(new java.awt.Dimension(460, 90));
        JpnlRunner3.setLayout(null);

        lblRunnerIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/Runner.png"))); // NOI18N
        JpnlRunner3.add(lblRunnerIcon3);
        lblRunnerIcon3.setBounds(10, 20, 90, 60);
        JpnlRunner3.add(prgRunner3);
        prgRunner3.setBounds(10, 0, 450, 90);

        getContentPane().add(JpnlRunner3);
        JpnlRunner3.setBounds(0, 200, 480, 90);

        JpnlRunner4.setPreferredSize(new java.awt.Dimension(460, 90));
        JpnlRunner4.setLayout(null);

        lblRunnerIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/immagini/Runner2.png"))); // NOI18N
        JpnlRunner4.add(lblRunnerIcon4);
        lblRunnerIcon4.setBounds(10, 10, 80, 70);
        JpnlRunner4.add(prgRunner4);
        prgRunner4.setBounds(10, 0, 450, 90);

        getContentPane().add(JpnlRunner4);
        JpnlRunner4.setBounds(2, 302, 470, 90);

        JpnlRunnerTimer4.setBackground(new java.awt.Color(209, 226, 243));
        JpnlRunnerTimer4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 226, 243)));
        JpnlRunnerTimer4.setPreferredSize(new java.awt.Dimension(150, 90));

        lblRunner4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblRunner4.setText("Runner 4");

        lblRunnerTimer4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRunnerTimer4.setText("0");

        javax.swing.GroupLayout JpnlRunnerTimer4Layout = new javax.swing.GroupLayout(JpnlRunnerTimer4);
        JpnlRunnerTimer4.setLayout(JpnlRunnerTimer4Layout);
        JpnlRunnerTimer4Layout.setHorizontalGroup(
            JpnlRunnerTimer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlRunnerTimer4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(lblRunnerTimer4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JpnlRunnerTimer4Layout.setVerticalGroup(
            JpnlRunnerTimer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnlRunnerTimer4Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(JpnlRunnerTimer4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner4)
                    .addComponent(lblRunnerTimer4))
                .addGap(28, 28, 28))
        );

        getContentPane().add(JpnlRunnerTimer4);
        JpnlRunnerTimer4.setBounds(480, 300, 150, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVelocitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVelocitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVelocitaActionPerformed

    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
     btnAvvia.setEnabled(false);//disattiva il bottone
     cmbVelocita.setEnabled(false);//disattiva la comboBox
       btnSospendere.setEnabled(true);//attiva il bottone
       btnRiprendi.setEnabled(true);//attiva il bottone
     boolean[] runnerPartito ={false,false,false};
     
     
     // imposta la velocità dalla comboBox
     int tempo=50;
     if (cmbVelocita.getSelectedItem().equals("Slow")) tempo=100;
     else if (cmbVelocita.getSelectedItem().equals("Fast")) tempo=10;
     
     //creazione Threads
     for (int i=0; i<4; i++){
         Runner r = new Runner(tempo);
         Thread t = new Thread(r);
          threads.add(t);
          runners.add(r);
     }
   
     threads.get(0).start();
      controllo = new Timer(tempo, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            
            // Richiama il metodo per far cambiare il valore delle progressBar
            AggiornaPrgb(runners.get(0), prgRunner1, lblRunnerTimer1);
            AggiornaPrgb(runners.get(1), prgRunner2, lblRunnerTimer2);
            AggiornaPrgb(runners.get(2), prgRunner3, lblRunnerTimer3);
            AggiornaPrgb(runners.get(3), prgRunner4, lblRunnerTimer4); 
            
          
            // Passaggio del testimone a 90, cambia il valore sull'array di bool facendolo partire 
            if (runners.get(0).getI() >= 90 && !runnerPartito[0]) {
                threads.get(1).start();
                runnerPartito[0] = true;
            }
            if (runners.get(1).getI() >= 90 && !runnerPartito[1]) {
                threads.get(2).start();
                runnerPartito[1] = true;
            }
            if (runners.get(2).getI() >= 90 && !runnerPartito[2]) {
                threads.get(3).start();
                runnerPartito[2] = true;
            }

            // alla fine quando l'ultimo thread finisce ferma il timer e riabilita i bottoni
            if (runners.get(3).getI() >= 100) {
                ((Timer)e.getSource()).stop(); // Spegne il timer
                btnAvvia.setEnabled(true);     // Riabilita i bottoni
                cmbVelocita.setEnabled(true);
            }
        }
    });
  controllo.start();
    }//GEN-LAST:event_btnAvviaActionPerformed

    private void btnSospendereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSospendereActionPerformed
      btnAvvia.setEnabled(false);
      btnSospendere.setEnabled(false);
      cmbVelocita.setEnabled(false);
      btnRiprendi.setEnabled(true);
      for (Runner r : runners){
          r.pausa();
      }
      
      
      
    }//GEN-LAST:event_btnSospendereActionPerformed

    private void btnRiprendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiprendiActionPerformed
        btnSospendere.setEnabled(true);
         btnRiprendi.setEnabled(false);
           for (Runner r : runners){
          r.riprendi();
      }
         
    }//GEN-LAST:event_btnRiprendiActionPerformed

    private void btnFermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermaActionPerformed
        
       
        /**
         * ferma tutti i runner 
         * ferma il timer 
         * resetta tutte le progress bar a zero 
         * cambia le label 
         * riabilita i bottoni
         */
        for (Runner r : runners) {
            r.reset();
        }
        if (controllo != null) {
            controllo.stop();
        }
        prgRunner1.setValue(0);
        prgRunner2.setValue(0);
        prgRunner3.setValue(0);
        prgRunner4.setValue(0);

        lblRunnerTimer1.setText("0");
        lblRunnerTimer2.setText("0");
        lblRunnerTimer3.setText("0");
        lblRunnerTimer4.setText("0");

        threads.clear();
        runners.clear();

        btnAvvia.setEnabled(true);
        cmbVelocita.setEnabled(true);
        btnRiprendi.setEnabled(false);
        btnSospendere.setEnabled(false);
    }//GEN-LAST:event_btnFermaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JThreadRelay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JThreadRelay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JThreadRelay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JThreadRelay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JThreadRelay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnlButton;
    private javax.swing.JPanel JpnlRunner1;
    private javax.swing.JPanel JpnlRunner2;
    private javax.swing.JPanel JpnlRunner3;
    private javax.swing.JPanel JpnlRunner4;
    private javax.swing.JPanel JpnlRunnerTimer1;
    private javax.swing.JPanel JpnlRunnerTimer2;
    private javax.swing.JPanel JpnlRunnerTimer3;
    private javax.swing.JPanel JpnlRunnerTimer4;
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnFerma;
    private javax.swing.JButton btnRiprendi;
    private javax.swing.JButton btnSospendere;
    private javax.swing.JComboBox<String> cmbVelocita;
    private javax.swing.JLabel lblRunner1;
    private javax.swing.JLabel lblRunner2;
    private javax.swing.JLabel lblRunner3;
    private javax.swing.JLabel lblRunner4;
    private javax.swing.JLabel lblRunnerIcon1;
    private javax.swing.JLabel lblRunnerIcon2;
    private javax.swing.JLabel lblRunnerIcon3;
    private javax.swing.JLabel lblRunnerIcon4;
    private javax.swing.JLabel lblRunnerTimer1;
    private javax.swing.JLabel lblRunnerTimer2;
    private javax.swing.JLabel lblRunnerTimer3;
    private javax.swing.JLabel lblRunnerTimer4;
    private javax.swing.JProgressBar prgRunner1;
    private javax.swing.JProgressBar prgRunner2;
    private javax.swing.JProgressBar prgRunner3;
    private javax.swing.JProgressBar prgRunner4;
    // End of variables declaration//GEN-END:variables
}
