/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

/**
 *
 * @author lucia
 */
public class JThreadRelay extends javax.swing.JFrame {

    /**
     * Creates new form JThreadRelay
     */
    public JThreadRelay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        prgRunner1 = new javax.swing.JProgressBar();
        prgRunner2 = new javax.swing.JProgressBar();
        prgRunner3 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        cmbVelocita = new javax.swing.JComboBox<>();
        btnAvvia = new javax.swing.JButton();
        btnSospendere = new javax.swing.JButton();
        btnRiprendi = new javax.swing.JButton();
        btnFerma = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblRunner1 = new javax.swing.JLabel();
        lblRunnerTimer1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblRunner2 = new javax.swing.JLabel();
        lblRunnerTimer2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblRunner3 = new javax.swing.JLabel();
        lblRunnerTimer3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        jPanel1.add(prgRunner1);
        prgRunner1.setBounds(10, 10, 450, 80);
        jPanel1.add(prgRunner2);
        prgRunner2.setBounds(10, 110, 450, 80);
        jPanel1.add(prgRunner3);
        prgRunner3.setBounds(10, 210, 450, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 310);

        cmbVelocita.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cmbVelocita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Slow", "Regular", "Fast" }));
        cmbVelocita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVelocitaActionPerformed(evt);
            }
        });

        btnAvvia.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnAvvia.setText("Avvia");

        btnSospendere.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnSospendere.setText("Sospendere");

        btnRiprendi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnRiprendi.setText("Riprende");

        btnFerma.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnFerma.setText("Ferma");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cmbVelocita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvvia)
                .addGap(53, 53, 53)
                .addComponent(btnSospendere)
                .addGap(35, 35, 35)
                .addComponent(btnRiprendi)
                .addGap(39, 39, 39)
                .addComponent(btnFerma)
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVelocita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRiprendi)
                    .addComponent(btnFerma)
                    .addComponent(btnSospendere)
                    .addComponent(btnAvvia))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 310, 650, 80);

        jPanel3.setBackground(new java.awt.Color(209, 226, 243));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 226, 243)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        lblRunner1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblRunner1.setText("Runner 1");

        lblRunnerTimer1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRunnerTimer1.setText(".");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(lblRunnerTimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner1)
                    .addComponent(lblRunnerTimer1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(480, 10, 150, 80);

        jPanel4.setBackground(new java.awt.Color(209, 226, 243));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 226, 243)));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 80));

        lblRunner2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblRunner2.setText("Runner 2");

        lblRunnerTimer2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRunnerTimer2.setText(".");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(lblRunnerTimer2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner2)
                    .addComponent(lblRunnerTimer2))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(480, 110, 150, 80);

        jPanel5.setBackground(new java.awt.Color(209, 226, 243));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 226, 243)));
        jPanel5.setPreferredSize(new java.awt.Dimension(150, 80));

        lblRunner3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblRunner3.setText("Runner 3");

        lblRunnerTimer3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblRunnerTimer3.setText(".");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRunner3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblRunnerTimer3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRunner3)
                    .addComponent(lblRunnerTimer3))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(480, 210, 150, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVelocitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVelocitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVelocitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JThreadRelay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JThreadRelay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JThreadRelay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JThreadRelay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JThreadRelay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnFerma;
    private javax.swing.JButton btnRiprendi;
    private javax.swing.JButton btnSospendere;
    private javax.swing.JComboBox<String> cmbVelocita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblRunner1;
    private javax.swing.JLabel lblRunner2;
    private javax.swing.JLabel lblRunner3;
    private javax.swing.JLabel lblRunnerTimer1;
    private javax.swing.JLabel lblRunnerTimer2;
    private javax.swing.JLabel lblRunnerTimer3;
    private javax.swing.JProgressBar prgRunner1;
    private javax.swing.JProgressBar prgRunner2;
    private javax.swing.JProgressBar prgRunner3;
    // End of variables declaration//GEN-END:variables
}
